url: "http://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-HolzerR" # the subpath of your site, e.g. /blog
title: "index" # the name of your site, e.g. ACME Corp.

collections:
  projets-animation:
    output: true
  projets-rap-2019:
    output: true


plugins:
    - jekyll-admin
